name: Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_ENV: test

jobs:
  # Code Quality Checks
  lint:
    name: ESLint & TypeScript Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run ESLint
      run: npm run lint:ci
    
    - name: TypeScript type check
      run: npx tsc --noEmit

  # Unit and Integration Tests
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests with coverage
      run: npm test -- --coverage --watchAll=false --passWithNoTests
    
    - name: Upload coverage reports
      if: matrix.node-version == '20.x'
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results-${{ matrix.node-version }}
        path: |
          coverage/
          *.log

  # Build and Package Test
  build:
    name: Build & Package Test
    runs-on: ubuntu-latest
    needs: [lint, test]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build package
      run: npm run build
    
    - name: Test package creation
      run: npm pack
    
    - name: Test package installation
      run: |
        mkdir test-install
        cd test-install
        npm init -y
        npm install ../n8n-nodes-plaid-*.tgz
        node -e "console.log('Package installed successfully')"
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
          dist/
          *.tgz

  # Security Audit
  security:
    name: Security Audit
    runs-on: ubuntu-latest
    continue-on-error: true
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run security audit
      run: npm audit --audit-level=moderate || echo "Security vulnerabilities found but continuing..."
    
    - name: Check for vulnerabilities
      run: npx audit-ci --config audit-ci.json || echo "Audit CI found issues but marked as non-blocking"

  # Performance Tests
  performance:
    name: Performance Tests
    runs-on: ubuntu-latest
    needs: [test]
    continue-on-error: true
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run performance tests
      run: |
        echo "Running performance benchmarks..."
        npm test -- --detectOpenHandles --logHeapUsage --verbose || echo "Performance tests completed with warnings"
    
    - name: Memory usage check
      run: |
        echo "Checking memory usage patterns..."
        node -e "
          const used = process.memoryUsage();
          console.log('Memory usage:');
          for (let key in used) {
            console.log(\`\${key}: \${Math.round(used[key] / 1024 / 1024 * 100) / 100} MB\`);
          }
        " || echo "Memory check completed"

  # Test Results Summary
  test-summary:
    name: Test Results Summary
    runs-on: ubuntu-latest
    needs: [lint, test, build, security, performance]
    if: always()
    
    steps:
    - name: Check test results
      run: |
        echo "## Test Summary" >> $GITHUB_STEP_SUMMARY
        echo "| Job | Status |" >> $GITHUB_STEP_SUMMARY
        echo "|-----|--------|" >> $GITHUB_STEP_SUMMARY
        echo "| Lint | ${{ needs.lint.result }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Tests | ${{ needs.test.result }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Build | ${{ needs.build.result }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Security | ${{ needs.security.result }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Performance | ${{ needs.performance.result }} |" >> $GITHUB_STEP_SUMMARY
        
        # Check core jobs (lint, test, build) - these must succeed
        CORE_SUCCESS=true
        if [[ "${{ needs.lint.result }}" != "success" ]]; then
          echo "❌ Lint job failed or was cancelled" >> $GITHUB_STEP_SUMMARY
          CORE_SUCCESS=false
        fi
        if [[ "${{ needs.test.result }}" != "success" ]]; then
          echo "❌ Test job failed or was cancelled" >> $GITHUB_STEP_SUMMARY
          CORE_SUCCESS=false
        fi
        if [[ "${{ needs.build.result }}" != "success" ]]; then
          echo "❌ Build job failed or was cancelled" >> $GITHUB_STEP_SUMMARY
          CORE_SUCCESS=false
        fi
        
        # Security and performance are optional - warn but don't fail
        if [[ "${{ needs.security.result }}" != "success" ]]; then
          echo "⚠️ Security audit had issues (non-blocking)" >> $GITHUB_STEP_SUMMARY
        fi
        if [[ "${{ needs.performance.result }}" != "success" ]]; then
          echo "⚠️ Performance tests had issues (non-blocking)" >> $GITHUB_STEP_SUMMARY
        fi
        
        if [[ "$CORE_SUCCESS" == "true" ]]; then
          echo "✅ All core tests passed!" >> $GITHUB_STEP_SUMMARY
          exit 0
        else
          echo "❌ Some core tests failed. Please check the logs." >> $GITHUB_STEP_SUMMARY
          exit 1
        fi 